services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: promptrip-frontend
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
